const Sizes ={
    TEXT_SIZE_SMALL:13,
    TEXT_SIZE_MIDLE:16,
    TEXT_SIZE_LARGE:22,
    WIDTH_BUTTON_SMALL:'60%',
    WIDTH_BUTTON_MIDLE:'70%',
    WIDTH_BUTTON_LARGE:'80%',
    HEIGHT_BUTTON_SMALL:50,
    HEIGHT_BUTTON_MIDLE:70,
    HEIGHT_BUTTON_LARGE:80,
}

export default Sizes;